export const RAT = "Undead Rat"
export const RABBIT = "Undead Rabbit"
export const SQUIRREL = "Undead Squirrel"
export const CHIPMUNK = "Undead Chipmunk"
export const HEDGEHOG = "Undead Hedgehog"
export const PORCUPINE = "Undead Porcupine"
export const RAVEN = "Undead Raven"
export const CROW = "Undead Crow"